# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{messenger}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Brandon Arbini"]
  s.date = %q{2010-02-04}
  s.default_executable = %q{messenger}
  s.description = %q{Messenger: easy message sending}
  s.email = %q{brandon@zencoder.tv}
  s.executables = ["messenger"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.markdown"
  ]
  s.files = [
    "README.markdown",
     "VERSION.yml",
     "lib/messenger.rb",
     "lib/messenger/campfire.rb",
     "lib/messenger/email.rb",
     "lib/messenger/errors.rb",
     "lib/messenger/jabber.rb",
     "lib/messenger/web.rb",
     "test/test_campfire.rb",
     "test/test_email.rb",
     "test/test_helper.rb",
     "test/test_jabber.rb",
     "test/test_messenger.rb",
     "test/test_web.rb"
  ]
  s.homepage = %q{http://github.com/zencoder/messenger}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Messenger: easy message sending}
  s.test_files = [
    "test/test_campfire.rb",
     "test/test_email.rb",
     "test/test_helper.rb",
     "test/test_jabber.rb",
     "test/test_messenger.rb",
     "test/test_web.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<trollop>, [">= 1.15"])
      s.add_runtime_dependency(%q<pony>, [">= 0.6"])
      s.add_runtime_dependency(%q<tmail>, [">= 1.2.6"])
      s.add_runtime_dependency(%q<mime-types>, [">= 1.16"])
      s.add_runtime_dependency(%q<httparty>, [">= 0.5.2"])
      s.add_runtime_dependency(%q<SystemTimer>, [">= 1.1.3"])
      s.add_runtime_dependency(%q<xmpp4r>, ["= 0.5"])
      s.add_runtime_dependency(%q<xmpp4r-simple>, ["= 0.8.8"])
      s.add_runtime_dependency(%q<json_pure>, [">= 1.2.0"])
    else
      s.add_dependency(%q<trollop>, [">= 1.15"])
      s.add_dependency(%q<pony>, [">= 0.6"])
      s.add_dependency(%q<tmail>, [">= 1.2.6"])
      s.add_dependency(%q<mime-types>, [">= 1.16"])
      s.add_dependency(%q<httparty>, [">= 0.5.2"])
      s.add_dependency(%q<SystemTimer>, [">= 1.1.3"])
      s.add_dependency(%q<xmpp4r>, ["= 0.5"])
      s.add_dependency(%q<xmpp4r-simple>, ["= 0.8.8"])
      s.add_dependency(%q<json_pure>, [">= 1.2.0"])
    end
  else
    s.add_dependency(%q<trollop>, [">= 1.15"])
    s.add_dependency(%q<pony>, [">= 0.6"])
    s.add_dependency(%q<tmail>, [">= 1.2.6"])
    s.add_dependency(%q<mime-types>, [">= 1.16"])
    s.add_dependency(%q<httparty>, [">= 0.5.2"])
    s.add_dependency(%q<SystemTimer>, [">= 1.1.3"])
    s.add_dependency(%q<xmpp4r>, ["= 0.5"])
    s.add_dependency(%q<xmpp4r-simple>, ["= 0.8.8"])
    s.add_dependency(%q<json_pure>, [">= 1.2.0"])
  end
end

